name: BossBarMonsterHP
version: '${project.version}'
main: me.noogs.BossBarMonsterHP
api-version: 1.18
author: [ Noogs ]
description: BossBarMonsterHP for Minecraft 1.18.1
commands:
    bbmp:
      description: BossBarMonsterHP Command
      usage: /<command>
